config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get '/tasks', to: 'tasks#index'
  get '/tasks/new', to: 'tasks#new'
  get '/tasks/:id', to: 'tasks#show', as: :task
  post '/tasks', to: 'tasks#create'
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch '/tasks/:id', to: 'tasks#update'
  delete '/tasks/:id', to: 'tasks#destroy'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def edit
    @task = Task.find(params[:id])
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path status: :see_other
  end
  private
  def task_params
    params.require(:task).permit(:name, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit To Do list</h1>
<%= form_with model: @task do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed%>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<div class="container">
<h1>Task List</h1>

<ul>
    <% @tasks.each do |task| %>
      <li>
        <label><%= link_to task.name, task_path(task) %></label>
        </li>
    <% end %>
  </ul>

<div class="add-task-btn">
    <%= link_to "Add a Task", tasks_new_path %>
  </div>
</div>

app/views/tasks/new.html.erb
<h1>Add to To Do list</h1>
<%= form_with model: @task do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed%>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<div class="container">
  <div class="d-flex justify-content-between align-items-center mb-4">
  <h1><%= @task.name %></h1>
  <div class="actions">
  <%= link_to edit_task_path(@task.id) , class: 'btn btn-light btn-sm border' do%>
  <i class="fa fa-pencil"></i> Edit this task
  <% end %>
</div>
</div>

<p><%=@task.details%></p>
<% if @task.completed %>
    <i class="fa fa-check-square-o"></i> Task completed
  <% else %>
    <i class="fa fa-square-o"></i> Task not completed
  <% end %>
  <div class="actions">
  <%= link_to "Return to Task List", tasks_path, class: 'btn btn-primary' %>
  <%= link_to "Delete", task_path(@task),class: 'btn btn-danger', data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
  </div>
</div>